### ISSUE TITLE
Como será desenvolvido o Blog?

### ISSUE THREAD

**Issue by theandersonn** [riojs-org/blog#1]
Já tem um planejamento para o desenvolvimento do Blog?
Bora agitar um tema em WordPress.

**Comment by afonsopacifer** [comment]
Ainda estamos pensando, 
mas a princípio seria com Jekyll :)

**Comment by raphamorim** [comment]
@theandersonn a ideia é começar usando jekyll para gerar o conteúdo estático.

A vantagem do jekyll é poder gerar build pelo próprio github a cada commit.

Porém o jekyll é em ruby e a org é RioJS, ou seja deveria ter repos apenas em javascript (? talvez ?). O que eu pessoalmente acho que tem pouca coisa a ver, pois o repo em questão é um blog.

Estamos abertos a sugestões :)

**Comment by theandersonn** [comment]
Tô começando meus experimentos com jekyll, bem inocentes por agora. 
Tb acho que para o desenvolvimento do blog fica livre de tecnologia/ferramenta.
Vou acompanhar as novidades no Repositório e na medida do possível colaborar.

**Comment by pedropolisenso** [comment]
@theandersonn @raphamorim @pedromarins @afonsopacifer Eu sugiro que seja Jekyll mesmo, até pela ideia do build ser pelo github, isso motiva quem for escrever a usar o github e passar por avaliações antes de darmos o merge, saca? Outra coisa, qualquer um vai poder escrever? tipo Tableless, Medium e etc? Porque criamos Team de escritores / admin e por aii vai

**Comment by afonsopacifer** [comment]
@pedropolisenso, O @pedromarins  sugeriu que tenhamos 15 escritores "fixos", para que cada um escreva um post a capa 15 dias, assim teriamos 1 Post por dia ao longo do mês, sem pesar para ninguém. Mas claro que deixar aberto para quem quiser contribuir tbm é essencial. 
O que você acha?

**Comment by pedropolisenso** [comment]
Irado! :+1:

**Comment by pedromarins** [comment]
Vamos criar um readme no projeto para documentar as ideias? @afonsopacifer e @tarcisiosilva podem cuidar disso?

**Comment by raphamorim** [comment]
Isso, melhor criar um `roadmap.md`  também, ou issues para apontar para release incial

**Comment by raphamorim** [comment]
Enfim, todos de acordo com o jekyll? Gostaria de já ter a base do blog pronta.

Vou desenvolver e mando o PR, e ai todos verificam se está válido :)

**Comment by pedropolisenso** [comment]
To de acordo com o @raphamorim, dai se puder manda pro gh-pages pra vermos o preview! Seria legal ter branch ein tipo: escritor, revisor algo assim ou não há necessidade?

CC: @pedromarins

**Comment by raphamorim** [comment]
Acho que não precisa. Podemos definir no manifesto do projeto, no readme mesmo.

A gente ainda adiciona um tópico de quem já publicou no blog

**Comment by raphamorim** [comment]
BTW: De arquitetura acho melhor o gitflow.
Todos de acordo?

**Comment by pedropolisenso** [comment]
Saquei, to de acordo!

**Comment by pedromarins** [comment]
Também! Senta o dedo e vamos botar isso no ar!

Em qui, 2 de jul de 2015 às 10:12, Pedro Polisenso notifications@github.com
escreveu:

**Comment by pedropolisenso** [comment]
Mais uma coisa, como teremos acesso ao domínio e o server do site atual? podemos ver com o Davidson o acesso, saca?

**Comment by pedromarins** [comment]
Sim! Já falei com ele e vou pedir para ele apontar o DNS para o meu
gerenciador para termos controle sobre isso.

Em qui, 2 de jul de 2015 às 10:16, Pedro Polisenso notifications@github.com
escreveu:

**Comment by afonsopacifer** [comment]
Blz, pessoal. Vou criar o Readme aqui

**Comment by raphamorim** [comment]
Justo, galera qualquer breaking, major change ou features longas. Acho válido passar por todo mundo usando Pull Request.

Até para manter a qualidade do projeto

**Comment by pedropolisenso** [comment]
Boa @raphamorim

**Comment by afonsopacifer** [comment]
@raphamorim Concordo

**Comment by theandersonn** [comment]
Já foram dicutidas todas funcionalidades? [arquitetura e fluxo]
Além dos artigos, tem a área dos slides das talks, parceiros etc...

**Comment by pedropolisenso** [comment]
@theandersonn O projeto aqui é somente do blog, ainda teremos a área do site q vai divulgar a comunidades e os eventos, sem falar nos projetos que temos em mente.

**Comment by theandersonn** [comment]
@pedropolisenso Ok!

**Comment by afonsopacifer** [comment]
Pessoal, criei uma issue para conversarmos sobre as postagens, podemos concentrar aqui a discussão sobre a construção do blog em si. 
De boa pessoal?

**Comment by tarcisiosilva** [comment]
blz , temos que ver o  planejamento  @afonsopacifer,  o  que acha de um hangout para começar a estruturar o  Blog ?

**Comment by pedropolisenso** [comment]
@tarcisiosilva e @afonsopacifer vejam o README.md como o @pedromarins pediu, deixa o @afonsopacifer da um start na estrutura e quando ele apresentar dando um PR vamos prosseguir com as melhorias!

**Comment by tarcisiosilva** [comment]
@pedropolisenso ,  blz

**Comment by tarcisiosilva** [comment]
@pedropolisenso  , Pedro  falou que vcs estão  tocando  o  site  ...
seria legal  ter uma estrutura única  , ou  seja uma identidade , de layout e cores ...
aí  montamos a estrutura do  blog  , em  conformidade do   site  ...
o  que acha :+1: ?

**Comment by pedropolisenso** [comment]
O blog é seria apenas mais um link do site, assim penso eu. O site do RioJS seria o mesmo que organizaria os eventos, armazenaria alguns links de palestras, falaria da comunidades, criaria projetos para a galera contribuir e teria o blog que será em Jekyll em um outro repositório fora do site mesmo!

CC: @raphamorim @pedromarins

**Comment by tarcisiosilva** [comment]
isso  , falo em  relação  da interface ...
não  em relação  ao  que representa !

mais vamos tocando  @pedropolisenso ;;

**Comment by pedropolisenso** [comment]
O Antonio ta pra apresentar um layout ja, vi um preview e ta ficando irado!

**Comment by afonsopacifer** [comment]
@tarcisiosilva podemos marcar esse hangout hoje a noite sem problemas mano, de boa para você?
obs: Adicionei um readme simples só para não ficar vazio :)

**Comment by tarcisiosilva** [comment]
blz mano @afonsopacifer ..
top mesmo  , vamos,   de boa ...

**Comment by raphamorim** [comment]
Referência: https://github.com/riojs-org/blog/pull/3

**Comment by pedropolisenso** [comment]
Galera só para fechar essa issue, porque ja temos ate a estrutura pronta só falta o layout ser definido. Se quiserem ver um preview da parada, faça o procedimento que o @raphamorim editou no README.md e veja em suas máquinas locais ok? 

PS: O clone será feito apenas uma vez, depois apenas atualizem seus repositórios locais como o do master no git. by

**Comment by raphamorim** [comment]
Boa @pedropolisenso
