### ISSUE TITLE
Frequência de postagens e redatores

### ISSUE THREAD

**Issue by afonsopacifer** [riojs-org/blog#2]
Vamos focar a discussão sobre os posts aqui :D

**Comment by pedropolisenso** [comment]
@riojs-org/blog é simples, precisamos definir e pensar como serão as postagens, certo? teremos escritores certos ou tipo, vai ser meio open e a galera vai mandando PR com seus post se curtimos aceitamos o PR e tal? Se tivermos escritores certo, vai ser preciso ter compromisso e estudar bastante para manter assuntos legais no blog e tbm pronto para tirar dúvidas, por outro lado deixando meio Open a galera pode tbm mandar seus PR com conteudos decentes ai analisamos e mantemos sempre posts com frequencia, ou podemos fazer das 2 maneiras.

**Comment by pedropolisenso** [comment]
Opções:

1º
Escritores certos, mais ou menos 15 seria um por dia e cada um postaria 2 por mês, precisando sempre estudar, nesse ponto é bom pelo fato de estarmos sempre estudando pra apresentar algo legal, sacam? e manter a organização e padrão do blog e equipe entrosada.

2º
Manter a ideia da 1º opção, porém permitindo que a galera da comunidade encaminhe seus posts e experiencias, sacam? Dai a gente iria avaliar o post e dar o merge ;)

PS: Acho que foi isso que quis dizer no comment de cima sahsuahsua!

**Comment by afonsopacifer** [comment]
Eu voto nos dois :D 

Sobre os 15 escritores, acho que se conseguirmos mesmo implementar isso seria algo muito incrível.
Nós temos que tentar descobrir se teremos mesmo 15 pessoas com tempo para escrever.

**Comment by pedromarins** [comment]
@afonsopacifer isso é fácil descobrir! É só abrirmos inscrição no grupo.

Sobre a proposta do @pedropolisenso a ideal é a 2 né? Mantermos o grupo focado produzindo e cada vez mais gente colaborando. Aos poucos vamos começar a ter 2 ~ 3 posts por dia. O que vai ser lindo!

**Comment by tarcisiosilva** [comment]
A ideia é essa Afonso  , mas não  acho difícil consegui 15 autores ...
ai  cada um cria um post por mês ...
assim  temos 1 post a cada 2 dias ....

**Comment by tarcisiosilva** [comment]
inicialmente , depois vamos  t muito  mais
