### ISSUE TITLE
Sugestão de novo fluxo para aceitação de código

### ISSUE THREAD

**Issue by raphamorim** [riojs-org/blog#4]
Galera, não é nenhum puxão de orelha.

Mas precisamos botar a casa em ordem. Um PR inicial ficou estagnado por 1 semana. Acho válido trabalharmos da seguinte forma: Para o merge, o PR deve passar na **validação de pelo menos 2 mantenedores**. Senão as coisas simplesmente não vão andar.

Precisamos ganhar velocidade, pois ainda há outro projeto além do blog. Simplesmente não pude caminhar mais com o projeto por falta de merge. Assim como quem fez o design não podia criar nada pois precisava do builder.

O que acham rapazes?

**Comment by pedropolisenso** [comment]
De acordo e nada mais que justo :+1: estamos lhe dando com projetos open, e caminhando para um produto que vai poder ajudar mais pessoas na comunidade. Sei dos compromissos de cada um, só vamos dar aquela olhadinha de leve e responder as issues negada ;)
