### ISSUE TITLE
Código de Conduta

### ISSUE THREAD

**Issue by leobalter** [riojs-org/blog#5]
Assim como no https://github.com/BarraJS/site_barrajs/pull/15, podia rolar um link para CoC no site do RioJS. Sem o site no ar eu fico enrolado para achar, mas posso montar PR tb.

**Comment by pedromarins** [comment]
Não temos site ainda. Só o eventick. E para esse meetup não teremos site. Vou divulgar o código de conduta na abertura do evento. E posso botar um link no eventick.

Manda o link ae @leobalter!

**Comment by pedropolisenso** [comment]
@leobalter @pedromarins assim que tivermos o site no ar, vamos oficializar isso!

CC: @riojs-org/blog
