### ISSUE TITLE
Hackday - RioJS

### ISSUE THREAD

**Issue by pedropolisenso** [riojs-org/blog#9]
[ATENÇÃO]

Queridos amigos que amo tanto @riojs-org/team-blog @raphamorim @pedromarins e eu estávamos vendo um dia inteiro de programação com a comunidade em favor do nosso site, blog e produtos que pretendemos criar. A ideia é trabalhar em cima de 3 projetos, mas não estaremos presos  1 projeto, cada um vai contribuir no projeto que quiser e se sentir a vontade, outra parada legal é que é aberto a comunidade e a nós aqui da organização. Ainda estamos vendo o melhor dia, mas vai rolar. Aqui vamos avisando vocês de tudo ok? quando definir fecharemos essa issue :+1:

**Comment by afonsopacifer** [comment]
Eu levo o energetico :zap:

**Comment by raphamorim** [comment]
A melhor data penso eu. Seria 15 de agosto. Uma semana antes do braziljs e na semana seguinte o @leobalter vai estar com a gente. Ai poderiamos esquentar com algum meetup.

O que acham rapazes?

**Comment by pedromarins** [comment]
Já consegui o espaço da Caelum, que cabem 20 cabeças. Estou tentando o
espaço da HE:labs, que cabem 30 e tem salas separadas, mas quadros, etc.
Esperando uma resposta hoje para fecharmos isso!

Em qua, 5 de ago de 2015 às 16:24, Raphael H. Amorim <
notifications@github.com> escreveu:

**Comment by pedropolisenso** [comment]
Isso é ótimo, ta fechado por mim! Só temos que combinar depois uma forma de papa!

**Comment by pedropolisenso** [comment]
Aee @raphamorim não ignorei não hahahaha, achei irado a ideia do meetup com o Balter aqui, podíamos ver para promover algo diferente ein!
